[package]
name = "party_cta"
edition = "2024"
license = "Apache 2.0"
authors = ["Miso Labs, Inc. (build@miso.network)"]

[dependencies]
partyos = { git = "https://github.com/misofm/partyos.git", rev = "735c72d2c7539dd71b6826d9abcb00b367a3e53c" }
