[package]
name = "party_cta"
edition = "2024"
license = "Apache 2.0"
authors = ["Miso Labs, Inc. (build@miso.network)"]

[dependencies]
partyos = { git = "https://github.com/misofm/partyos.git", rev = "3626ee19e42cf8df5ecea59cd5be6cb5a1538cc1" }
