[package]
name = "party_roles"
edition = "2024"
license = "Apache 2.0"
authors = ["Miso Labs, Inc. (build@miso.network)"]

[dependencies]
partyos = { git = "https://github.com/misofm/partyos.git", rev = "3626ee19e42cf8df5ecea59cd5be6cb5a1538cc1" }
typed_set = { git = "https://github.com/unconfirmedlabs/typed_set.git", rev = "b37474cbde166b7ddf8a3b615cd89f90182ace6f" }
